name: PlayWright_Job

# Define when the workflow should run
on:
  schedule:
    # Run at 1:30 PM IST (8:00 AM UTC)
    - cron: '30 8 * * *'  
    # Run at Monday 10 AM UTC
    - cron: '0 4 * * 1'
    # Run at Friday 5 PM UTC
    - cron: '30 11 * * 5'
  
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Choose which test to run'
        required: true
        default: 'allure-report'
        options:
          - allure-report
          - regression
          - webTests
          - typeScriptTest

jobs:
  run-typeScriptTest:
    runs-on: ubuntu-latest

    # Only run when 'test_type' is 'typeScriptTest'
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.test_type == 'typeScriptTest' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      # Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run typeScriptTest
        run: npm run typeScriptTest

  run-regression:
    runs-on: ubuntu-latest

    # Only run when 'test_type' is 'regression'
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.test_type == 'regression' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      # Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run regression tests
        run: npm run regression

  run-allure-report:
    runs-on: ubuntu-latest

    # Only run when 'test_type' is 'allure-report'
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.test_type == 'allure-report' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      # Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run allure-report tests
        run: npm run allure-report

  run-webTests:
    runs-on: ubuntu-latest

    # Only run when 'test_type' is 'webTests'
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.test_type == 'webTests' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      # Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run webTests
        run: npm run webTests

  # Manual test job to allow user input selection
  manual-test:
    runs-on: ubuntu-latest

    # Run this job only if triggered manually via `workflow_dispatch`
    if: ${{ github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      # Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run selected test (Manual)
        run: |
          if [[ "${{ github.event.inputs.test_type }}" == "allure-report" ]]; then
            npm run allure-report
          elif [[ "${{ github.event.inputs.test_type }}" == "regression" ]]; then
            npm run regression
          elif [[ "${{ github.event.inputs.test_type }}" == "webTests" ]]; then
            npm run webTests
          elif [[ "${{ github.event.inputs.test_type }}" == "typeScriptTest" ]]; then
            npm run typeScriptTest
          fi