name: PlayWright_Job

# Define when the workflow should run
on:
  schedule:
    - cron: '30 8 * * *'  # Run at 1:30 PM IST (8:00 AM UTC)
    - cron: '0 4 * * 1'  # Run at Monday 10 AM UTC
    - cron: '30 11 * * 5'  # Run at Friday 5 PM UTC
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Choose which test to run'
        required: true
        default: 'allure-report'
        options:
          - allure-report
          - regression
          - webTests
          - typeScriptTest

jobs:
  run-typeScriptTest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      # Add step to install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run typeScriptTest
        run: npm run typeScriptTest
        if: ${{ github.event.inputs.test_type == 'typeScriptTest' }}

  run-regression:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      # Add step to install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run regression tests
        run: npm run regression
        if: ${{ github.event.inputs.test_type == 'regression' }}

  run-allure-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      # Add step to install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run allure-report tests
        run: npm run allure-report
        if: ${{ github.event.inputs.test_type == 'allure-report' }}

  manual-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      # Add step to install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run selected test (Manual)
        run: |
          if [[ "${{ github.event.inputs.test_type }}" == "allure-report" ]]; then
            npm run allure-report
          elif [[ "${{ github.event.inputs.test_type }}" == "regression" ]]; then
            npm run regression
          elif [[ "${{ github.event.inputs.test_type }}" == "webTests" ]]; then
            npm run webTests
          elif [[ "${{ github.event.inputs.test_type }}" == "typeScriptTest" ]]; then
            npm run typeScriptTest
          fi